// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhz4FDRU-WUSeQ-owbgRSt62MBoCm2RCw',
    appId: '1:1075007431985:web:f8ed455a3e7c05fbc8bc10',
    messagingSenderId: '1075007431985',
    projectId: 'ecole229-ba68a',
    authDomain: 'ecole229-ba68a.firebaseapp.com',
    storageBucket: 'ecole229-ba68a.appspot.com',
    measurementId: 'G-Z98FQVG4V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDac4E9za65X-4nx1UNaCua_HPxJIodIcw',
    appId: '1:1075007431985:android:87b09c3e20088b79c8bc10',
    messagingSenderId: '1075007431985',
    projectId: 'ecole229-ba68a',
    storageBucket: 'ecole229-ba68a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIzrXQbrO5QFhwStiV9VVVfKnTZ0RXT0Y',
    appId: '1:1075007431985:ios:ae29d5b2b72adb2ec8bc10',
    messagingSenderId: '1075007431985',
    projectId: 'ecole229-ba68a',
    storageBucket: 'ecole229-ba68a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIzrXQbrO5QFhwStiV9VVVfKnTZ0RXT0Y',
    appId: '1:1075007431985:ios:58ce864d8bde106ac8bc10',
    messagingSenderId: '1075007431985',
    projectId: 'ecole229-ba68a',
    storageBucket: 'ecole229-ba68a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
