// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIf7kthIHfj-dxClQVzp3oeURs0iYkuvQ',
    appId: '1:296226227239:web:fa4a8f6c5e3b950641ba02',
    messagingSenderId: '296226227239',
    projectId: 'ecole229-db480',
    authDomain: 'ecole229-db480.firebaseapp.com',
    storageBucket: 'ecole229-db480.appspot.com',
    measurementId: 'G-17ZCQFYM2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl4-s0ckJEmcSDdKhRxnFejRlVZ8R2pFE',
    appId: '1:296226227239:android:cc764c50aaf5c3e441ba02',
    messagingSenderId: '296226227239',
    projectId: 'ecole229-db480',
    storageBucket: 'ecole229-db480.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7-7FQUVbCSBu8BEJ7fo0lDTISIcrBMwA',
    appId: '1:296226227239:ios:b1b764f17e192eac41ba02',
    messagingSenderId: '296226227239',
    projectId: 'ecole229-db480',
    storageBucket: 'ecole229-db480.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7-7FQUVbCSBu8BEJ7fo0lDTISIcrBMwA',
    appId: '1:296226227239:ios:5ef588127d60299741ba02',
    messagingSenderId: '296226227239',
    projectId: 'ecole229-db480',
    storageBucket: 'ecole229-db480.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
